config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "login#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	 	validates_presence_of :date
		validates_presence_of :obs
		validates_presence_of :status
end

app/models/user.rb
class User < ApplicationRecord
	  validates_presence_of :login
	  validates_presence_of :passwd
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  before_action :set_login, only: [:verify]

	def index
		template
		@user = User.new(:login,:passwd)	
	end

	def verify
		
	end 
	private 
	def template 
		render layout: "template"
	end 
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:date, :obs, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json


  def index    
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :passwd)
    end

    def template
      render layout:"template"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciador</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar fixed: :top, brand: "GERENCIADOR" do %>
    <%= menu_group do %>
        <%= menu_item "Usuários", new_user_path %>
        <%= menu_item "Projetos", new_schedule_path %>   
    <% end %>
    
	<% end %>
   <br/>
   <br/>
   <br/>
    <%= yield %>
  </body>
</html>

app/views/layouts/template.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciador</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <body>
   <div class="container">
		<%= nav_bar brand: "Sistema"  %>
 	<%= yield %>
 	</div>
  </body>
</html>

app/views/login/index.html.erb
<%= form_for @user do |f| %>
  <%= f.label :login %>:
  <%= f.text_field :passwdv%><br />

  <%= f.submit %>
<% end %>

app/views/schedules/_form.html.erb
<%= form_for(schedule) do |f| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default">
  <div class="panel-heading">
    Cadastro Projeto
  </div>
  <div class="panel-body">
 <div class="row">
  <div class="form-group">
  <div class="field" style="margin-left:40px;">
    <%= f.label :data %>
    <%= f.date_select :date ,class:"form-control" %>
  </div>
  </div>
  </div>
<div class="row">
<div class="form-group">
  <div class="field col-md-4" rows="3" style="margin-left:40px;">
    <%= f.label :descricao %>
    <%= f.text_area :obs ,class:"form-control" %>
  </div>
  </div>
</div>
<div class="row">
<div class="form-group">
  <div class="field" style="margin-left:40px;">
    <%= f.label :status %>
    <%= f.check_box :status  %>
  </div>
  </div>
  </div>
<div class="row">
  <div class="actions" style="margin-left:40px;">
    <%= f.submit "salvar",class:"btn btn-success"%>
    <%= link_to 'lista', schedules_path , class:"btn btn-default" %>
  </div>  
<% end %>
</div>
</div>
</div>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'mostrar', @schedule ,class:"btn btn-default" %> |
<%= link_to 'voltar', schedules_path ,class:"btn btn-default"  %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Obs</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.date %></td>
        <td><%= schedule.obs %></td>
        <td><%= schedule.status %></td>
        <td><%= link_to 'mostrar', schedule ,class:"btn btn-default" %></td>
        <td><%= link_to 'Editar', edit_schedule_path(schedule), class:"btn btn-info" %></td>
        <td><%= link_to 'excluir', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'criar novo projeto', new_schedule_path, class:"btn btn-warning" %>

app/views/schedules/new.html.erb
<%= render 'form', schedule: @schedule %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @schedule.obs %>
</p>

<p>
  <strong>Status:</strong>
  <%= @schedule.status %>
</p>

<%= link_to 'editar', edit_schedule_path(@schedule) ,class:"btn btn-default" %> |
<%= link_to 'voltar', schedules_path , class:"btn btn-default" %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default">
  <div class="panel-heading">
  Novo Usuário
</div>
<div class="panel-body">
 <div class="row">
  <div class="form-group">
  
  <div class="field col-md-2">
    <%= f.label :login %>
    <%= f.text_field :login , class:"form-control" %>
  </div>

</div>
</div>

 <div class="row">
  <div class="form-group">
  
  <div class="field col-md-2">
    <%= f.label :passwd %>
    <%= f.password_field :passwd, class:"form-control" %>
  </div>

</div>
</div>
</div>
 <div class="row">
  <div class="field col-md-2" style="margin-left:20px;">  
    <%= f.submit "salvar", class:"btn btn-success" %>
    <%= link_to 'lista', users_path ,class:"btn btn-default" %>  
  </div>
  </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>
<%= link_to 'mostrar', @user , class:"btn btn-default" %> |
<%= link_to 'voltar', users_path ,class:"btn btn-default" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Login</th>
      <th>Passwd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.passwd %></td>
        <td><%= link_to 'mostrar', user , class:"btn btn-default" %></td>
        <td><%= link_to 'editar', edit_user_path(user), class:"btn btn-info" %></td>
        <td><%= link_to 'excluir', user, method: :delete, data: { confirm: 'tem certeza que deseja excluir?' } , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'criar novo usuario', new_user_path, class:"btn btn-default" %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Passwd:</strong>
  <%= @user.passwd %>
</p>

<%= link_to 'editar', edit_user_path(@user) ,class:"btn btn-default" %> |
<%= link_to 'voltar', users_path ,class:"btn btn-default" %>